TOKEN_DURATION = 60 * 60 * 24   # 1 day
SQLALCHEMY_DATABASE_URL = 'sqlite:///./sql_app.db'
UNLOCK_OFFICE_URL = "http://192.168.0.151"
UNLOCK_OFFICE_PARAMS = {"key": "St1Nidz@13"}
MQTT_SERVER = "ujagaga.tplinkdns.com"
MQTT_INTERCOM_TOPIC = "intercom_door"
MQTT_OFFICE_LIGHT_TOPIC = "office_light"
MQTT_PORT = 1883
MQTT_USER = "ujagaga"
MQTT_PASS = "S1mpleTh1ngsM@tter"
USTREAMER_USER = "uStreamerUser"
TMP_DIR = "/tmp/officeserver"
USTREAMER_STATIC_DIR_SRC = "../tools/ustreamer_static"
USTREAMER_STATIC_DIR_DST = "ustreamer_static"
OFFICE_LIGHT_URL = "http://192.168.0.153"
LOCAL_USER_NAME = "local"
WEATHER_API_KEY = "6b15e16bb3dc4ba1b063d0836d56ce44"
WEATHER_API_URL = "http://api.weatherbit.io/v2.0/current"
WEATHER_ICON_URL = "https://www.weatherbit.io/static/img/icons"
DEFAULT_CITY = "NOVI SAD"
WEATHER_NOT_READABLE_SECONDS = (60 * 30)
